sonar.projectKey=notes-application
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_844246377d36a3aa41130fe28d6e79dec8b5154b