sonar.projectKey=notes-application
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info